### ISSUE TITLE
Macports instead of/in addition to Homebrew?

### ISSUE THREAD

**Issue by terrylb** [drduh/macOS-Security-and-Privacy-Guide#195]
Isn't Macports <http://macports.org> a better choice from a security standpoint? Installing software via port does require root permissions but port installed software is sandboxed and has no dependencies on anything Apple installs--like older versions of rsync, python, etc.

**Comment by sp-1234** [comment]
> Installing software via port does require root permissions

And this is a problem. All software tends to have bugs, including installation scripts. Especially when we talk about software written in C.
So running them as root, of course, increases attack surface.

**Comment by terrylb** [comment]
Wouldn't this also be the case for other package managers like rpm and yum?

**Comment by aaronvan** [comment]
I've been using Brew for several years and installs almost always work. Occasionally, there is a little configuration required. Just my two shillings.

**Comment by Eitot** [comment]
Neither are particularly secure. MacPorts is also falling behind, in my own observations, and Homebrew still insists on removing the root permissions from `/usr/local`, so that they can install things without using sudo (see #145). Installing Homebrew into a local directory is safer, but it comes at the cost of having to compile some packages yourself.

**Comment by sp-1234** [comment]
>Wouldn't this also be the case for other package managers like rpm and yum?

Of course. AFAIK If you use them, you have to trust that the installation routines (of every package you install) are free from bugs or malicious behavior, because they will run by root user (or other user with similar permissions) and therefore any misbehavior can pwn the system.
And ensuring this is not easy, because someone has to audit *all* packages.

**Comment by terrylb** [comment]
It sounds like there are a couple of thoughts here: Use Brew because it doesn't require root to install, and beware of package managers. 

I've got nothing against Brew but if it alters /use/local to be writeable by anybody, that doesn't seem like improved security.

I get it that using a package manager like Macports, Brew, rpm, yum, etc. means extending trust to someone else. Security and convenience are mutually exclusive so we all make choices. For me on my production machines, Macports was the right choice. Ports are simple TCL script files that are easily inspected. Typically they point to the open source project's current source with its checksum and instruct the system's compiler to use /opt/local as the destination. It will also do the same for any required dependencies so your package is self-contained. This is useful because it's safe from Apple's updates. Also, it allows you to be more secure since historically Apple has been slow to patch/update packages. rsync comes to mind.

Eitot, I'm not sure what you mean by Macports "falling behind." At last check it has ~22,000 ports, active development, a very friendly and responsive mailing list and the project lead has support from Apple. I have no affiliation other than being a satisfied user for the last 10 years.

**Comment by Eitot** [comment]
@terrylb: As I said, my observations. I switched from Homebrew to MacPorts and found it rather frustrating. Some packages that I used were outdated, many that I wanted were not available. I had to wait for weeks until they fixed a bug in one makefile of a package. Homebrew is a lot more responsive and approachable IMO and trivial bugs are fixed in a matter of hours/minutes when you report them.

@marcus-cr: They switched from modifying `/usr/local` to modifying `/usr/local/bin`, `/usr/local/lib` etc. instead, a couple of months ago. They went from bad to slightly less bad. Homebrew does change the permissions for you when you install it using their installation script.

**Comment by rawtaz** [comment]
For the sake of completeness, let's not forget about [pkgsrc](http://www.netbsd.org/docs/pkgsrc/introduction.html#intro.platforms).

It has supported the Mac since 2001, works great on OS X and is a nice and well maintained package system. Both compiles and has binaries, lives in its own space in the filesystem, like Macports does.

**Comment by sp-1234** [comment]
@rawtaz does it require root for installing/updating/removing packages?

**Comment by rawtaz** [comment]
@sp-1234 It's been a while since I ran it now, so I honestly can't say for sure, but I highly doubt that you need root privileges, since normally you just run it under one base path such as /usr/pkg (which you may need root privs to create of course, but you can move it to another place), and after that you just work under that directory when compiling and installing. It'd be if you wanted or needed to place files outside that tree at some point, I guess. At least I don't remember having to be root all the time, that's for sure :)

**Comment by drduh** [comment]
PRs welcome. I am not a MacPorts user, thus will not be included it myself.
