### ISSUE TITLE
Ports worth blocking for incoming connection? (Firewall)

### ISSUE THREAD

**Issue by nadavP3** [drduh/macOS-Security-and-Privacy-Guide#229]
Any thoughts on adding some common ports worth blocking via firewall? such as [this](http://blog.shadowserver.org/2014/03/28/the-scannings-will-continue-until-the-internet-improves/) list:

> 
> CharGEN (UDP/19)
> DNS (UDP/53) (Open Resolver Project)
> Kad (UDP/6429)
> MS-SQL (UDP/1434)
> NetBIOS (UDP 137 to 139)
> NTP Mode 6 (UDP/123) (Open NTP Project)
> NTP Mode 7 (UDP/123)
> QOTD (UDP/17)
> Quake Network Protocol (UDP/26000 and UDP/27960)
> SNMPv2 (UDP/161) (Open SNMP Project)
> SSDP (UDP/1900) (Open SSDP Project)
> Steam Protocol (Many – UDP/27015)
> 
> 
> **Botnet Protocols:**
> Conficker (TCP/445)
> Gameover Zeus (Takedown by the FBI on 2014-05-30)
> Sality
> Zeroaccess
> 
> 
> **Protocols That Should not be Exposed:**
> CWMP (TCP/7547)
> DB2 (UDP/523)
> Elastic Search (TCP/9200)
> HDFS (TCP/50070, TCP/50075, TCP/50090, TCP/50105, TCP/50030, TCP/50060)
> IPMI (UDP/623)
> LDAP (UDP/389)
> mDNS (UDP/5353)
> MemCached (TCP/11211)
> MongoDB (TCP/27017, TCP/27018, TCP/27019, TCP/28017)
> NAT-PMP (UDP/5351)
> NetBIOS (TCP/137 to 139)
> Portmapper (UDP/111)
> RDP (TCP/3389 and UDP/3389)
> REDIS (TCP/6379)
> rlogin (TCP/513)
> SSDP (TCP/1900)
> TFTP (UDP/69)
> Telnet (TCP/23)
> Telnet, Alternative (TCP/2323)
> VNC (TCP/5900)
> XDMCP (UDP/177)
> 
> 
> **Protocols That are Vulnerable:**
> ISAKMP (UDP/500)
> Netcore/Netis Router (UDP/53413)
> SSL/FREAK (TCP/443)
> SSLv3 (TCP/443)
> Synful Knock (TCP/80)

**Comment by rawtaz** [comment]
Better to *allow* the things you want than to block everything you don't want.


28 maj 2017 kl. 06:46 skrev Nadav Appel <notifications@github.com>:

**Comment by drduh** [comment]
There's no need to block ports for two reasons: a) most Macs are already behind a NAT and thus not exposed to the whole Internet, and b) one would have to do something explicit to enable services listening on those ports and thus assumed to know what one is doing. Better yet, block all ports you don't need and go by the whitelisting model rawtaz@ alluded to; this is possible with Little Snitch.

**Comment by techydude** [comment]
@nadavP3 
If you enable the Software Firewall built in to Mac, then default operation is to BLOCK EVERYTHING (incoming), unless an exception has been specifically setup (which is not uncommon for specific apps).

Additionally as DrDuh responded, most client computers are behind a NAT router, and thus it's impossible for internet scans to reach you - unless you have both (a) a Mac Software Firewall exception for that port, AND (b) that port routed through to your specific IP address, either manually setup in your router (which you would only do deliberately) or via Mac's NATPMP.

That link you referenced is primarily aimed at 'servers' that typically have a network i/f directly connected to the internet.

Lastly, blocking outgoing traffic from a client computer from specific ports is generally annoying, because when you do want to use something it won't work, until you remember "Oh yeah, I blocked all those ports last year" - or worse, you forgot entirely and band your head against the keyboard and create a bunch of noise that other people have to troubleshoot for you.

The entire notion of a firewall that allows all traffic except that which you manually choose to block (in the context of a domestic & small-business networks) was a quaint idea that died 20 years ago.

**Comment by nadavP3** [comment]
Ahh, I see, thanks for the detailed explanation :)
