### ISSUE TITLE
Homebrew - Where to Install Apps?

### ISSUE THREAD

**Issue by EvilistMonkey** [drduh/macOS-Security-and-Privacy-Guide#279]
In the user accounts section it says it's preferable to install apps into the ~/Applications folder when possible. I installed homebrew with my regular account and followed the instructions to install it into ~/homebrew. 

Whenever I install an app homebrew tries to move it into /Applications and asks for a password to do so. I'm not logged in as admin and I'm not in the sudoers group so I just have to ctrl-c out of it. It does seem to install just fine into ~/homebrew/caskroom though and the couple apps I've tested so far are working properly. 

I guess I'm trying to figure out if this is normal to have to bypass the /Applications password request each time I install an app with homebrew. Also, will I have to symlink each app into the ~/Applications folder now? The guide is a bit confusing between the 'user accounts' and 'homebrew' sections on what the ideal configuration should be.

**Comment by savyajha** [comment]
Please put `export HOMEBREW_CASK_OPTS="--appdir=~/Applications"` in whatever shell you use. That will cure it.

**Comment by EvilistMonkey** [comment]
Thanks, that does indeed do the trick. I suppose I should have read the brew documentation closer.

On a related note, I found this method that allows a standard user use homebrew by taking ownership of the /usr/local folder.
https://gist.github.com/kevinkarwaski/94bfb1e83ee20cf80c13

I tried it and it works. If I used the appdir option with this method would it be a better solution? It would allow me to keep the admin/standard user setup and use homebrew. Is there any danger in giving a standard account this ownership? 

There's a caution in brew documentation that says:

> do yourself a favor and install to /usr/local. Some things may not build when installed elsewhere. One of the reasons Homebrew just works relative to the competition is because we recommend installing to /usr/local. Pick another prefix at your peril!> 

So, I just want to make sure I'm not going to regret this in the future.

**Comment by savyajha** [comment]
@EvilistMonkey The entire point of this convoluted dance is to not install in `/usr/local`. In standard Unix shells, of which both `bash` and `zsh` are specimens, if you try to run executable, the shell first searches in `/usr/local/bin` before searching in `/bin` and `/usr/bin`. This guide assumes you do not wish for an untrusted third party to install any binary in `/usr/local/bin` precisely because of this hierarchy.

As an example, suppose you installed some program into `/usr/local` not knowing it was malicious. You wanted to install, say, neovim, a text editor not present on the Mac. Unfortunately, the malicious program also installed an evil `bash` binary. So now, whenever you start up your terminal, you're not getting Apple's system-provided `bash` binary, you're getting the malicious `/usr/local/bin/bash` instead. Even if you do this without administrative privileges (by chowning `/usr/local` to some non-administrative user), the primacy of `/usr/local/bin` over `/bin` means that a rogue program can potentially cause a lot of grief. It just can't crash your computer or utterly mess with your system. It might still be able to look at your documents or photos, or other sensitive data.

By using `~/homebrew/bin` as a source of your binaries and adding this to the *end* of your `$PATH` variable, you're adding a layer of security. The `$PATH` variable works sequentially. If you define something at the beginning, it will be given primacy. If you define something at the end, it will be looked into at the very end. Even if our malicious program installed an evil `bash` binary in this directory, our defining of `$PATH` means that Apple's system provided binary will be given preference over the malicious one, because the shell will search in every other location first before looking at `~/homebrew/bin`. Therefore you preclude the accidental running of a malicious program installed without your knowledge by putting your homebrewed programs in a location at the end of `$PATH`.

In my opinion, there's no need to do this. This guide hardens your system to a very ridiculous extent, and not trusting homebrew is the functional equivalent of not trusting the Apple App Store. You would be much better served by using the `su` utility to log into an administrator shell, and using that shell to work with homebrew. I assume you know how to work with `su`, so I won't explain it here. Having a separate user account which only handles homebrew is also not a bad idea.

**Comment by EvilistMonkey** [comment]
Thanks very much for the explanation, it clear up a lot of confusion for me. Are you still putting apps into your standard user's ~/Applications folder? Does that matter?

**Comment by savyajha** [comment]
Yes, I do. My personal setup is a normal user for everyday tasks, and an admin user which I use for homebrew. I also install to `/usr/local`. If I can't trust homebrew, then I can't trust anything they install anyway.

Using `~/Applications` for your GUI programs (which homebrew cask installs) doesn't affect security, because you don't access GUI programs from the terminal. Typically, you access them through Finder or through Launchpad. The security problem of `/usr/local/bin` getting preference and launching a malicious program is only there when you launch programs from the terminal.
