### ISSUE TITLE
Does APFS make evicting FV keys redundant?

### ISSUE THREAD

**Issue by crichez** [drduh/macOS-Security-and-Privacy-Guide#283]
Apple's [File System Programming Guide](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/) updated February 20th mentions the following under "File System Basics/Security/Files[...]":
> When the user puts the computer to sleep or shuts it down, the decryption keys are destroyed to prevent unauthorized access to the disk’s contents.

The [Apple File System Guide](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/Features/) also suggests user data is protected even on a decrypted volume:
> Multi-key encryption ensures the integrity of user data. Even if someone were to compromise the physical security of the device and gain access to the device key, they still couldn't decrypt the user's files.

I don't know of any technical information to confirm that. Is there precedent for this (file systems that support per-file multi-key encryption)?

**Comment by metagoose** [comment]
None of those links work. I am really interested in getting more information on this.

**Comment by metagoose** [comment]
[New](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) links [https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/Features/Features.html](url)

**Comment by metagoose** [comment]
> It's state of the art block level encryption, however file system level encryption such as what will be offered by the upcoming APFS is fundamentally better.
In a block level encryption each sector is encrypted below the file system. Doing the naïve thing of encrypting each sector with the encryption key is fundamentally insecure. This is called the EBC mode of operation. There's a nice picture of a penguin on wikipedia encrypted with ECB which demonstrates this:

https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation...

Secure mode of operations generally try to propagate the result of previously encrypted blocks to the next ones. But this approach is not really suitable for mass storage devices. You cannot re-encrypt all the sectors behind the one you just changed. That's just impractical, since writing to sector #0 amounts to rewrite the entire disk.

So in practice schemes like AES-XTS are used. They work by having some kind of way of "tweaking" the encryption, so that it is different for each block (avoiding the pitfalls of ECB), but in a way which allows random access to sectors (i.e. in a way that is predictable). AES-XTS is a tradeoff for this special use case but it is not as robust as more classical modes of operations which would typically be used in an encrypted filesystem.

Details about AES-XTS issues: https://sockpuppet.org/blog/2014/04/30/you-dont-want-xts/

**Comment by kylehotchkiss** [comment]
Not confirming this is true, but if so, this is beautiful. I have been eyeing the filevault key deletion/hibernate option for my laptops knowing how much trouble people have had with it (https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/124)

**Comment by drduh** [comment]
Interesting, does anyone have more information or have done an analysis to verify this?

**Comment by simmac** [comment]
Sorry for necromancing this issue, but did anyone else find any info other than this single mention in the APFS-Guide-document about this?
