### ISSUE TITLE
Tor Browser and Homebrew Cask

### ISSUE THREAD

**Issue by EvilistMonkey** [drduh/macOS-Security-and-Privacy-Guide#284]
I'm wondering why you recommend downloading Tor Browser from torproject.org rather than installing from brew cask. Is it for being able to get the signature file and verify with gpg? Is the option 'HOMEBREW_CASK_OPTS=--require-sha' not enough to verify the dmg?

I'm starting to wonder if I should be manually installing certain GUI apps rather than using cask. Are there any pros/cons to using brew cask at all?

**Comment by Stop-playing** [comment]
I actually had a similar question in this context, and a slightly broader topic as well.  If I download an app using a browser, and then attempt to open it for the first time I get a warning from the OS saying "X.app was downloaded from Y.com are you sure you want to open it?"   With brew cask, I don't get that same warning when opening a GUI application for the first time.

Now, trying into EvillistMonkey's question, I am not sure if/how the lack of warning I discussed above might relate to proper verification of downloadable images.   In other words, is brew cask, even with the sha-sum flag enabled still inadequate to protect against compromised mirrors or servers?  Should the precaution taken with Tor be expanded then to verify all apps (that provide pgp signatures) using pgp, instead of relying on brew cask's internal shasum checking?

**Comment by crichez** [comment]
I can't answer specifically about how brew cask works, but you should favor OpenPGP signatures over checksums when possible: (tl;dr: a checksum protects integrity, but a pgp signature protects authenticity.)

A checksum will only protect you if your download is corrupted or your mirror is malicious. However since you are obtaining the sum and the file from the same source, you are still subject to man-in-the-middle attacks.

You could argue the same about downloading PGP public keys & signatures, since you can get them all via torproject.org. But there is one feature of OpenPGP that is meant to guard against this: [the web of trust](https://www.gnupg.org/gph/en/manual/x547.html). 
If you look at [Tor's documentation on verifying signatures](https://www.torproject.org/docs/verifying-signatures.html.en), they mention you can download the Debian developers keychain to verify the signatures on the Tor Browser Developers signing key. This means that an attacker would have to compromise multiple sources to forge a public key, making it impractical.

**Comment by EvilistMonkey** [comment]
I'm strongly considering getting rid of cask altogether and reinstalling/verifying everything manually. Most GUI apps already have an auto-update system and I've also noticed that cask doesn't install the latest versions of some apps. Not sure why that is, but it makes me lose confidence in the whole "brew update && brew upgrade" process. 

I guess my question now is - is there any actual benefit to using brew cask aside from install speed (which I don't care about)?

**Comment by savyajha** [comment]
Cask doesn't update GUI apps. It merely installs them. Cask is simply there for people who want to install and uninstall GUI apps from the command line. It does nothing else.

**Comment by drduh** [comment]
Downloading Tor Browser from the official distribution allows one to verify file integrity with GPG. Not sure about Cask and I don't typically install non-CLI software through Homebrew.

@Stop-playing the dialog you mention is from Gatekeeper; specifically, the browser is attaching some metadata to downloaded files to flag them on first open. See https://github.com/drduh/macOS-Security-and-Privacy-Guide#metadata-and-artifacts. This is not all that useful of a security measure, in my opinion.

Like @crichez says, PGP signatures and verifying their trust is perhaps the most secure and verifiable way of guaranteeing software integrity.
