### ISSUE TITLE
MacOS HighSierra Kernel Panics

### ISSUE THREAD

**Issue by MegaTraveller** [drduh/macOS-Security-and-Privacy-Guide#300]
Hi,

I admit, that I have no clue so far. But since switching to a new Box, it seems that there have to be a Problem within the settings that sends my box into kernel panic.

I have the feeling, but I am not sure, that the issue has something to do with the FileVault Section. The new box takes sometimes up to 2 Minutes to wake up after sleep. working with the finder on the network causes kernel panics, coping files causes kernel panics. Running docker and virtual box, causes kernel panic, while moving large amounts of files.

I will reinstall the whole system once more. Hoping the issue will be gone, and applying only one step after another to figure out what causes this. If I figure it out I will post an update.

**Comment by TraderStf** [comment]
I got one yesterday, first since dozen of months. Was in Safari, made a right-click on an amazon's product picture.
Can't reproduce. I have all latest updates.
The only ~common thing with you is wake up after a long sleep (4+hours), it's not slow but quite often CrashPlan's menu item crashes and from time to time BBEdit.

**Comment by MegaTraveller** [comment]
Made a fresh reinstall and this time I passed on the File Vault modifications. They worked on my old box like a charm, but I tried now two times and I am running into the same problems again. Maybe the settings need to be different, I will check the site and see if there will be some changes in this section.
