### ISSUE TITLE
Screensaver settings not honored in Catalina

### ISSUE THREAD

**Issue by maiertech** [drduh/macOS-Security-and-Privacy-Guide#352]
I noticed that on macOS Catalina the two settings

```
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
```

listed in [this section of the README](https://github.com/drduh/macOS-Security-and-Privacy-Guide#miscellaneous) do not seem to have any effect.

When I make a change in the corresponding tab in the Security & Privacy settings in the System Preferences UI, both values above do not change while the UI settings are honored.

Or the other way round, you cannot override more lax settings from the UI with the two commands above.

This might be related to Catalina's new security model. I am wondering if there is another way to enforce these settings via the command-line.

**Comment by drduh** [comment]
Is this still the case for others and on Big Sur?

**Comment by tshu-w** [comment]
> Is this still the case for others and on Big Sur?

Yes, macOS Big Sur 11.4.

**Comment by andrewcrook** [comment]
I find the same for other features  that I read in peoples dot files.
if you can’t, you can always try using AppleScript

**Comment by drduh** [comment]
Resolving to inactivity. If anyone knows the correct screensaver settings in recent macOS versions, please send a PR.

**Comment by andrewcrook** [comment]
@drduh as far as I can see in macOS 14 they no longer exist because the screen saver settings have been replaced by the lock screen settings therefore will always ask for a password if locked . There are some settings for "Start Screen Saver when inactive” and "Require password after screen saver begins or display is turned off” which are time related.

**Start Screen Saver when inactive**
‘idleTime’.    integer '60'     "$HOME/Library/Preferences/ByHost/com.apple.screensaver.<GUID>.plist”

**Require password after screen saver begins or display is turned off**
I haven't been able to workout the location of this yet I am thinking that it might not be stored in a plist?
