### ISSUE TITLE
Misleading information in Google Chrome section

### ISSUE THREAD

**Issue by sryze** [drduh/macOS-Security-and-Privacy-Guide#416]
> The login passwords are encrypted and in order to access them, a user's Google account password is required. You can use your Google account to sign to your Chrome customized settings from other devices while retaining your the security of your passwords

I don't think this statement is correct - when you try to view passwords in Chrome, it actually asks for the password to the OS user running the browser, not the password to the Google Account as mentioned here

**Comment by drduh** [comment]
It's been a while since I've used these Chrome features, can anyone else confirm and possibly update accordingly?

**Comment by jotai73** [comment]
It is true that you are prompted for your computer account password when
you try to view any passwords in your Chrome password manager, but you have
to be logged into Chrome in order to access the password manager. In
Chrome's "You and Google" > "Sync and Google Services" menu, you're given
the option to encrypt synced passwords with your Google account or encrypt
data with your own sync passphrase.
